@startuml
class Cat {
    + Name : string
    + Cat()
    + Cat(name:string, date:DateTime)
    + WriteToConsole() : void
}
class "List`1"<T> {
}
Cat --> "DateOfBirth" DateTime
Cat o-> "Children<Cat>" "List`1"
@enduml
