@startuml
!include .\\assignment1\sort.puml
!include .\\CRC_CSD-01\Program.puml
!include .\\CRC_CSD-02\Program.puml
!include .\\CRC_CSD-03\Program.puml
!include .\\CRC_CSD-04\Program.puml
!include .\\snake\Program.puml
!include .\\CRC_CSD-05\MyBusiness\Program.puml
!include .\\CRC_CSD-05\PetLibrary\Cat.puml
!include .\\CRC_CSD-05\PetLibrary\Dog.puml
!include .\\CRC_CSD-05\PetLibrary\OwnPets.puml
!include .\\assignment1\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\assignment1\obj\Debug\net6.0\assignment1.AssemblyInfo.puml
!include .\\assignment1\obj\Debug\net6.0\assignment1.GlobalUsings.g.puml
!include .\\CRC_CSD-01\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-01\obj\Debug\net6.0\CRC_CSD-00.AssemblyInfo.puml
!include .\\CRC_CSD-01\obj\Debug\net6.0\CRC_CSD-00.GlobalUsings.g.puml
!include .\\CRC_CSD-01\obj\Debug\net6.0\CRC_CSD-01.AssemblyInfo.puml
!include .\\CRC_CSD-01\obj\Debug\net6.0\CRC_CSD-01.GlobalUsings.g.puml
!include .\\CRC_CSD-02\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-02\obj\Debug\net6.0\CRC_CSD-01.AssemblyInfo.puml
!include .\\CRC_CSD-02\obj\Debug\net6.0\CRC_CSD-01.GlobalUsings.g.puml
!include .\\CRC_CSD-02\obj\Debug\net6.0\CRC_CSD-02.AssemblyInfo.puml
!include .\\CRC_CSD-02\obj\Debug\net6.0\CRC_CSD-02.GlobalUsings.g.puml
!include .\\CRC_CSD-03\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-03\obj\Debug\net6.0\CRC_CSD-02.AssemblyInfo.puml
!include .\\CRC_CSD-03\obj\Debug\net6.0\CRC_CSD-02.GlobalUsings.g.puml
!include .\\CRC_CSD-03\obj\Debug\net6.0\CRC_CSD-03.AssemblyInfo.puml
!include .\\CRC_CSD-03\obj\Debug\net6.0\CRC_CSD-03.GlobalUsings.g.puml
!include .\\CRC_CSD-04\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-04\obj\Debug\net6.0\CRC_CSD-04.AssemblyInfo.puml
!include .\\CRC_CSD-04\obj\Debug\net6.0\CRC_CSD-04.GlobalUsings.g.puml
!include .\\snake\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\snake\obj\Debug\net6.0\snake.AssemblyInfo.puml
!include .\\snake\obj\Debug\net6.0\snake.GlobalUsings.g.puml
!include .\\CRC_CSD-05\MyBusiness\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-05\MyBusiness\obj\Debug\net6.0\MyBusiness.AssemblyInfo.puml
!include .\\CRC_CSD-05\MyBusiness\obj\Debug\net6.0\MyBusiness.GlobalUsings.g.puml
!include .\\CRC_CSD-05\PetLibrary\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-05\PetLibrary\obj\Debug\net6.0\PetLibrary.AssemblyInfo.puml
!include .\\CRC_CSD-05\PetLibrary\obj\Debug\net6.0\PetLibrary.GlobalUsings.g.puml
@enduml
