@startuml
!include .\\assignment1\sort.puml
!include .\\assignment2_1\sort.puml
!include .\\assignment2_2\Program.puml
!include .\\CRC_CSD-01\Program.puml
!include .\\CRC_CSD-02\Program.puml
!include .\\CRC_CSD-03\Program.puml
!include .\\CRC_CSD-04\Program.puml
!include .\\CRC_CSD-06\Cat.puml
!include .\\CRC_CSD-06\Program.puml
!include .\\CRC_CSD-08\Program.puml
!include .\\CRC_CSD-09\Program.puml
!include .\\snake\Program.puml
!include .\\assignment3\GeometryLibrary\Cuboid.puml
!include .\\assignment3\GeometryLibrary\Cylinder.puml
!include .\\assignment3\GeometryLibrary\Edge.puml
!include .\\assignment3\GeometryLibrary\Geometry.puml
!include .\\assignment3\GeometryLibrary\Tetrahedron.puml
!include .\\assignment3\GeometryLibrary\Vertex.puml
!include .\\assignment3\ObjectComputation\Program.puml
!include .\\CRC_CSD-05\MyBusiness\Program.puml
!include .\\CRC_CSD-05\PetLibrary\Cat.puml
!include .\\CRC_CSD-05\PetLibrary\Dog.puml
!include .\\CRC_CSD-05\PetLibrary\OwnPets.puml
!include .\\CRC_CSD-07\GraphLibrary\Edge.puml
!include .\\CRC_CSD-07\GraphLibrary\Graph.puml
!include .\\CRC_CSD-07\GraphLibrary\Vertex.puml
!include .\\CRC_CSD-07\SocialNet\Program.puml
!include .\\assignment1\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\assignment1\obj\Debug\net6.0\assignment1.AssemblyInfo.puml
!include .\\assignment1\obj\Debug\net6.0\assignment1.GlobalUsings.g.puml
!include .\\assignment2_1\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\assignment2_1\obj\Debug\net6.0\assignment1.AssemblyInfo.puml
!include .\\assignment2_1\obj\Debug\net6.0\assignment1.GlobalUsings.g.puml
!include .\\assignment2_2\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\assignment2_2\obj\Debug\net6.0\assignment2_2.AssemblyInfo.puml
!include .\\assignment2_2\obj\Debug\net6.0\assignment2_2.GlobalUsings.g.puml
!include .\\CRC_CSD-01\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-01\obj\Debug\net6.0\CRC_CSD-01.AssemblyInfo.puml
!include .\\CRC_CSD-01\obj\Debug\net6.0\CRC_CSD-01.GlobalUsings.g.puml
!include .\\CRC_CSD-02\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-02\obj\Debug\net6.0\CRC_CSD-02.AssemblyInfo.puml
!include .\\CRC_CSD-02\obj\Debug\net6.0\CRC_CSD-02.GlobalUsings.g.puml
!include .\\CRC_CSD-03\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-03\obj\Debug\net6.0\CRC_CSD-03.AssemblyInfo.puml
!include .\\CRC_CSD-03\obj\Debug\net6.0\CRC_CSD-03.GlobalUsings.g.puml
!include .\\CRC_CSD-04\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-04\obj\Debug\net6.0\CRC_CSD-04.AssemblyInfo.puml
!include .\\CRC_CSD-04\obj\Debug\net6.0\CRC_CSD-04.GlobalUsings.g.puml
!include .\\CRC_CSD-06\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-06\obj\Debug\net6.0\CRC_CSD-06.AssemblyInfo.puml
!include .\\CRC_CSD-06\obj\Debug\net6.0\CRC_CSD-06.GlobalUsings.g.puml
!include .\\CRC_CSD-08\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-08\obj\Debug\net6.0\CRC_CSD-08.AssemblyInfo.puml
!include .\\CRC_CSD-08\obj\Debug\net6.0\CRC_CSD-08.GlobalUsings.g.puml
!include .\\CRC_CSD-09\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-09\obj\Debug\net6.0\CRC_CSD-09.AssemblyInfo.puml
!include .\\CRC_CSD-09\obj\Debug\net6.0\CRC_CSD-09.GlobalUsings.g.puml
!include .\\snake\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\snake\obj\Debug\net6.0\snake.AssemblyInfo.puml
!include .\\snake\obj\Debug\net6.0\snake.GlobalUsings.g.puml
!include .\\assignment3\GeometryLibrary\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\assignment3\GeometryLibrary\obj\Debug\net6.0\GeometryLibrary.AssemblyInfo.puml
!include .\\assignment3\GeometryLibrary\obj\Debug\net6.0\GeometryLibrary.GlobalUsings.g.puml
!include .\\assignment3\ObjectComputation\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\assignment3\ObjectComputation\obj\Debug\net6.0\ObjectComputation.AssemblyInfo.puml
!include .\\assignment3\ObjectComputation\obj\Debug\net6.0\ObjectComputation.GlobalUsings.g.puml
!include .\\CRC_CSD-05\MyBusiness\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-05\MyBusiness\obj\Debug\net6.0\MyBusiness.AssemblyInfo.puml
!include .\\CRC_CSD-05\MyBusiness\obj\Debug\net6.0\MyBusiness.GlobalUsings.g.puml
!include .\\CRC_CSD-05\PetLibrary\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-05\PetLibrary\obj\Debug\net6.0\PetLibrary.AssemblyInfo.puml
!include .\\CRC_CSD-05\PetLibrary\obj\Debug\net6.0\PetLibrary.GlobalUsings.g.puml
!include .\\CRC_CSD-07\GraphLibrary\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-07\GraphLibrary\obj\Debug\net6.0\GraphLibrary.AssemblyInfo.puml
!include .\\CRC_CSD-07\GraphLibrary\obj\Debug\net6.0\GraphLibrary.GlobalUsings.g.puml
!include .\\CRC_CSD-07\SocialNet\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\CRC_CSD-07\SocialNet\obj\Debug\net6.0\SocialNet.AssemblyInfo.puml
!include .\\CRC_CSD-07\SocialNet\obj\Debug\net6.0\SocialNet.GlobalUsings.g.puml
@enduml
